apiVersion: v1
kind: Namespace
metadata:
  name: purge-ldl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: purge-ldl-data
  namespace: purge-ldl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # uncomment and set to match your cluster
