apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: purge-ldl
  labels:
    app.kubernetes.io/name: purge-ldl
    app.kubernetes.io/component: app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: purge-ldl.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: purge-ldl
                port:
                  number: 80
