apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: purge-ldl-data
  labels:
    app.kubernetes.io/name: purge-ldl
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # set in overlay if needed
